# dependabot.yml file with updates
# disabled for npm

version: 2
updates:
  # Configuration for npm
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 0
